server:
  port: 9080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

amazonProperties:
  endpointUrl: https://storage.yandexcloud.net
  accessKey: accessKey
  secretKey: secretKey
  bucketName: bucketName
  region: ru-central1



